packages:
  - "apps/*"
  - "packages/*"

catalog:
  # React
  react: ^19.2.4
  react-dom: ^19.2.4

  # TypeScript
  typescript: ^5.9.3

  # Tailwind CSS
  tailwindcss: ^4.1.4
  "@tailwindcss/postcss": ^4.1.4

  # Types
  "@types/react": ^19.2.0
  "@types/react-dom": ^19.2.0
  "@types/node": ^25.2.0
